export const motivationalMessages = [
    "💪 Hãy hoàn thành bài học để mở khóa nội dung tiếp theo!",
    "🌟 Kiến thức mới đang chờ bạn khám phá, hãy hoàn thành bài học này!",
    "🚀 Tiến bộ từng bước nhỏ sẽ tạo nên thành công lớn!",
    "📚 Mỗi bài học hoàn thành là một bước tiến trên con đường tri thức!",
    "🧠 Học tập đều đặn mỗi ngày sẽ giúp bạn tiến xa hơn!",
    "✨ Bạn đang làm rất tốt! Hãy tiếp tục nỗ lực nhé!",
    "🏆 Kiên trì là chìa khóa dẫn đến thành công!",
    "🎯 Mục tiêu đang ở rất gần, đừng bỏ cuộc nhé!",
    "🔥 Sự chăm chỉ hôm nay sẽ mang lại thành quả ngày mai!",
    "🌱 Kiến thức là hạt giống của thành công, hãy gieo trồng mỗi ngày!",
    "💡 Mỗi bài học là một viên gạch xây nên tương lai vững chắc!",
    "🧗‍♂️ Chỉ cần bạn không ngừng leo lên, đỉnh cao sẽ chờ bạn chinh phục!",
    "📖 Tri thức không giới hạn, hãy tiếp tục khám phá!",
    "💎 Bạn chính là kho báu, hãy trau dồi tri thức mỗi ngày!",
    "🏋️‍♂️ Học tập là quá trình rèn luyện trí tuệ mạnh mẽ!",
    "🚴‍♀️ Mỗi ngày một chút, bạn sẽ vượt xa chính mình!",
    "🧳 Kiến thức là hành trang quý giá nhất cho mọi chuyến đi!",
    "🌻 Học hỏi mỗi ngày giúp bạn nở rộ như một bông hoa tri thức!",
    "🪄 Mỗi bài học sẽ biến bạn thành phiên bản tốt hơn của chính mình!",
    "💼 Đầu tư vào tri thức là khoản đầu tư sinh lời nhất!",
    "⚡ Hãy kiên trì! Thành công chỉ dành cho những người bền bỉ!",
    "🚢 Học tập là con tàu đưa bạn đến những chân trời mới!",
    "🧭 Mỗi kiến thức mới là một la bàn dẫn lối thành công!",
    "🪜 Từng bài học sẽ đưa bạn lên một bậc cao hơn!",
    "🌍 Mỗi ngày học một điều mới, thế giới sẽ rộng mở hơn với bạn!",
    "🥇 Mỗi bước tiến nhỏ hôm nay sẽ đưa bạn tới vinh quang ngày mai!",
    "🏃‍♂️ Cứ tiếp tục học, bạn sẽ thấy mình tiến xa hơn mỗi ngày!",
    "🧬 Tri thức là sức mạnh, hãy tiếp tục trau dồi nó!",
    "📈 Thành công bắt đầu từ những nỗ lực không ngừng nghỉ!",
    "🧱 Mỗi bài học là một viên gạch trong lâu đài ước mơ!",
    "🎉 Hoàn thành bài học hôm nay, bạn đã tiến gần hơn tới mục tiêu!",
    "🚨 Đừng để sự lười biếng làm chậm bước tiến của bạn!",
    "🌈 Học tập sẽ mở ra cho bạn những cánh cửa cơ hội đầy sắc màu!",
    "🧹 Xóa bỏ lười biếng, đón nhận tri thức mới mỗi ngày!",
    "🎵 Mỗi bài học là một nốt nhạc trên bản giao hưởng thành công!",
    "⚙️ Học tập giúp bánh xe sự nghiệp quay trơn tru hơn!",
    "📅 Đặt mục tiêu mỗi ngày và kiên trì hoàn thành nhé!",
    "🧠 Bộ não của bạn sẽ ngày càng mạnh mẽ nhờ học tập chăm chỉ!",
    "🏔️ Không có đỉnh núi nào quá cao nếu bạn không ngừng tiến bước!",
    "🕰️ Hãy biến từng phút giây học tập thành những khoảnh khắc giá trị!",
    "🎁 Mỗi bài học là một món quà dành tặng cho chính bạn!",
    "🌟 Kiến thức sẽ giúp bạn tỏa sáng ở bất cứ nơi đâu!",
    "🧡 Học tập là cách tốt nhất để yêu thương chính bản thân mình!",
    "🎯 Đừng bỏ lỡ cơ hội chinh phục tri thức hôm nay!",
    "🏖️ Học tập hôm nay, thành công ngày mai!",
    "🛠️ Tri thức là công cụ giúp bạn xây dựng tương lai vững chắc!",
    "🦾 Bạn mạnh mẽ hơn mỗi khi hoàn thành một bài học mới!",
    "⚓ Kiến thức là neo đậu cho sự tự tin!",
    "🏹 Hãy nhắm đến mục tiêu tri thức và bắn trúng bằng sự kiên trì!",
    "🌸 Mỗi bài học sẽ giúp bạn nở rộ như một bông hoa tươi đẹp!",
    "🎬 Đừng chỉ xem, hãy tham gia vào hành trình học tập của mình!",
    "🚦 Dừng lại để nghỉ, nhưng đừng quên tiếp tục tiến bước!",
    "🧩 Mỗi bài học là một mảnh ghép hoàn hảo cho bức tranh thành công!",
    "🛤️ Học tập là con đường đưa bạn đến đích mơ ước!",
    "🌋 Nhiệt huyết hôm nay sẽ bùng nổ thành thành công ngày mai!",
    "🎈 Hãy để tri thức nâng bạn bay cao hơn mỗi ngày!",
    "🧗‍♀️ Mỗi bài học là một bước leo lên đỉnh vinh quang!",
    "🛡️ Kiến thức là tấm khiên vững chắc bảo vệ bạn trong cuộc sống!",
    "💡 Đừng ngại thử thách, vì mỗi bài học sẽ soi sáng con đường của bạn!",
    "🗺️ Khám phá tri thức như một nhà thám hiểm dũng cảm!",
    "🎠 Hành trình học tập đầy sắc màu, hãy vui vẻ trên đường đi!",
    "💎 Học tập chăm chỉ, bạn sẽ trở thành phiên bản rực rỡ nhất của chính mình!",
    "⚖️ Kiến thức là chìa khóa cân bằng cho cuộc sống hạnh phúc!",
    "🧬 Mỗi bài học sẽ làm bạn trở nên toàn diện hơn!",
    "🧙‍♂️ Học tập là phép thuật có thật của cuộc sống!",
    "🎡 Kiến thức là vòng quay vô tận, hãy tham gia và trải nghiệm!",
    "🧤 Hãy chuẩn bị cho mọi thử thách bằng tri thức vững vàng!",
    "🚂 Học tập đều đặn, bạn sẽ đến ga thành công sớm thôi!",
    "🏖️ Học tập là chuyến du lịch đến miền tri thức kỳ thú!",
    "🎲 Tri thức sẽ giúp bạn kiểm soát vận may của chính mình!",
    "🧗 Kiên trì học tập là con đường ngắn nhất đến thành công!",
    "📢 Hãy lắng nghe tri thức và hành động ngay hôm nay!",
    "🎯 Mục tiêu lớn bắt đầu từ từng bài học nhỏ!",
    "📦 Tri thức là món quà vô giá dành cho người chăm học!",
    "🎯 Hãy học mỗi ngày để không ngừng nâng cao bản thân!",
    "🧠 Mỗi bài học sẽ giúp bạn sắc bén hơn từng ngày!",
    "🪁 Học tập chính là cánh diều nâng cao ước mơ của bạn!",
    "🔭 Học tập giúp bạn nhìn xa hơn và hiểu sâu hơn!",
    "⚓ Kiến thức giúp bạn neo đậu vững chắc giữa sóng gió cuộc đời!",
    "🚁 Mỗi bài học sẽ đưa bạn đến một tầm cao mới!",
    "🏖️ Học tập là tấm vé đưa bạn tới bãi biển thành công!",
    "🧪 Hãy để mỗi bài học là một thí nghiệm thành công của bạn!",
    "📜 Tri thức sẽ viết nên câu chuyện đẹp nhất của bạn!",
    "💼 Sự nghiệp vững chắc bắt đầu từ nền tảng tri thức!",
    "🚴‍♂️ Đạp từng vòng tri thức để về đích thành công!",
    "🎤 Học tập chăm chỉ, thành công sẽ cất lời chúc mừng bạn!",
    "🧱 Tri thức giúp bạn xây dựng giấc mơ bằng những viên gạch chắc chắn!",
    "🌟 Đừng bỏ qua cơ hội học tập, vì nó sẽ dẫn bạn đến ánh sáng!",
    "🌳 Học tập là cách tốt nhất để nuôi dưỡng trí tuệ và tâm hồn!",
    "🧗‍♂️ Dù khó khăn, hãy nhớ: mỗi bài học đưa bạn gần hơn tới đỉnh cao!",
    "🌈 Sau mỗi bài học là một chân trời mới đang chờ bạn!",
    "🚦 Bắt đầu ngay hôm nay, mỗi bài học sẽ đưa bạn tới đích!",
    "🏁 Học tập chăm chỉ là con đường ngắn nhất để cán đích thành công!",
    "📚 Tri thức là kho báu vô giá, hãy khám phá nó mỗi ngày!",
    "🪴 Kiến thức giống như cây xanh — càng chăm sóc càng vững mạnh!",
    "🏆 Đích đến vinh quang luôn dành cho người học tập kiên trì!",
    "📌 Học tập đều đặn là bí quyết giữ lửa đam mê thành công!",
    "🚀 Đẩy lùi giới hạn bản thân bằng sức mạnh của tri thức!"
];
